name = "DavidsFMM3DBIE"
uuid = "a605821a-dd2a-4a50-9744-ebcb664eb958"
authors = ["David Stein <dstein@flatironinstitute.org>"]
version = "0.0.1"

[deps]
Bijections = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Bijections = "0.1.9"
LinearAlgebra = "1.11.0"
StaticArrays = "1.9.13"
julia = "1.10"
